### PR TITLE
Add combat stuff.

### PR DESCRIPTION
**Pull request by phulin**

### CODE REVIEW

**Comment by pastelmind** [comment]
It might be time to discuss development tooling.

@gausie and I have been using Yarn. @phulin I assume you are using NPM, since you added `package-lock.json`.

Maintaining both `package-lock.json` and `yarn.lock` would be tedious and error-prone. I suggest we agree to adopt one package manager.

(I mentioned it in #13 but it's awaiting a review.)

**Comment by phulin** [comment]
Oh, this is probably just me having no idea what I'm doing with JS tooling. I'll switch to Yarn.

**Review by pastelmind — DISMISSED** [review]
It compiles fine for me. Good work!

**Comment by gausie** [comment]
This is amazing. Minor points

* Could you add some jsdocs to the functions you've written? They are super cool but I think they need to be well documented to be well used.
* Did you run prettier on this? `yarn run format` should do it.
* Can you remove `print`s? I think we should consider adding debug logging in the future but I think having unavoidable prints is bad form.

**Comment by phulin** [comment]
Yep, yarn run format only touches files not in my PR. Should probably address that in a separate PR.

**Comment by phulin** [comment]
Adding a couple more things and then it should be ready to merge in my view.

**Review by gausie — APPROVED** [review]
Fantastic. I don't think we need types in the jsdoc but this is great!

**Pull request merged**
