### PR TITLE
Overhaul property system for speed.

### PR DESCRIPTION
**Pull request by phulin**
While really, really nice, our well-typed property system is very nonperformant while doing live development in VS Code or other IDEs. These edits maintain near-full fidelity to the original code; we only lose type checking accuracy on multiple-property functions like `withProperties`.

### CODE REVIEW

**Comment by phulin** [comment]
API question: should `getBoolean` return null if the property doesn't exist? Or should there be a default default of false?

**Comment by phulin** [comment]
I reverted back to the existing behavior so as not to cause like 500 errors in garbo.

**Review by pstalcup — APPROVED** [review]

**Comment by phulin** [comment]
Requesting your review sam whenever you have time + energy + inclination, no rush.

**Comment by horrible-little-slime** [comment]
It's worth mentioning that this devours/fulfills #187

**Pull request merged**
